Разметка html главной страницы и страницы каталога по гостиницам
htmlacademy-htmlcss/1413529-sedona-1 pull request #2
Opened 2023-08-10 21:31 UTC by Natali34

Домашнее задание по разделу Разметка

2023-08-11 17:01 UTC, Kartaviy-arteom requested changes

2023-08-11 17:01 UTC, Kartaviy-arteom commented on index.html
> +  <a class="navigation-logo" href="index.html">
нужно соблюдать вложенность элементов, структуру отступов в разметке

2023-08-11 17:01 UTC, Kartaviy-arteom commented on index.html
> +  <img class="index-title-background" src="#" alt="Фотография гор">
второе изображение будет в стилях, оно декоративное. Нужно убрать

2023-08-11 17:01 UTC, Kartaviy-arteom commented on index.html
> +  <p class="index-title_text_2">Опытный персонал и качественное обслуживание!</p>
лучше перенести в услуги

2023-08-11 17:01 UTC, Kartaviy-arteom commented on index.html
> +    <input type="email" name="newsletter-email" placeholder="Ваш e-mail">
label и input обязателен к заполнению

2023-08-11 17:01 UTC, Kartaviy-arteom commented on hotels.html
> +  </label>
объединить в группу аналогично радиокнопкам

2023-08-11 17:01 UTC, Kartaviy-arteom commented on hotels.html
> +<button class="button-reset" type="submit">СБРОСИТЬ</button>
type неверный

2023-08-11 17:01 UTC, Kartaviy-arteom commented on hotels.html
> +  <button class="button-favorites" type="submit">В ИЗБРАННОЕ</button>
тип неверный

2023-08-11 17:01 UTC, Kartaviy-arteom commented on hotels.html
> +<a class="rating" href="#">Рейтинг: 8.5</a>
не нужна ссылка

2023-08-11 17:01 UTC, Kartaviy-arteom commented on hotels.html
> +    <p>Гостиница</p>
картинка и заголовок будут ссылками

2023-08-14 19:09 UTC, Kartaviy-arteom commented on hotels.html
> +            <input class="range-slider-input" type="range" name="price" min="0" max="9000">
это лишнее

2023-08-14 19:09 UTC, Kartaviy-arteom commented on hotels.html
> +            <input class="number-slider-input" type="number" name="min" min="0" placeholder="от">
пояснение для элементов нужно добавить

2023-08-14 19:09 UTC, Kartaviy-arteom commented on hotels.html
> +        <span class="visually-hidden">Показать список</span>
список

2023-08-14 19:09 UTC, Kartaviy-arteom commented on hotels.html
> +        </li>
откула эта ссылка

2023-08-14 19:09 UTC, Kartaviy-arteom commented on hotels.html
> +        </li>
откула эта ссылка

2023-08-16 06:01 UTC, Kartaviy-arteom approved these changes

2023-08-16 06:01 UTC, merged

2023-08-19 09:49 UTC, Natali34 reviewed
Графика для всех страниц

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +  <button class="button-favorites" type="submit">В ИЗБРАННОЕ</button>
тип исправила на button

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +<a class="rating" href="#">Рейтинг: 8.5</a>
убрала ссылку

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +<button class="button-reset" type="submit">СБРОСИТЬ</button>
исправила на reset

2023-08-19 09:49 UTC, Natali34 commented on index.html
> +  <a class="navigation-logo" href="index.html">
Структуру отформатировала, единственно из-за этого комментарии съехали

2023-08-19 09:49 UTC, Natali34 commented on index.html
> +  <p class="index-title_text_2">Опытный персонал и качественное обслуживание!</p>
Перенесла

2023-08-19 09:49 UTC, Natali34 commented on index.html
> +  <img class="index-title-background" src="#" alt="Фотография гор">
Убрала строку с изображением для отражения в с стилях CSS.

2023-08-19 09:49 UTC, Natali34 commented on index.html
> +    <input type="email" name="newsletter-email" placeholder="Ваш e-mail">
Связала label с for проставила id в input

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +  </label>
Отработала

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +    <p>Гостиница</p>
Скорректировала.

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +        </li>
Внесла правки, убрала ссылку, т.к. в макете нет сслыки на предыдущую страницу

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +        </li>
Внесла правки, убрала ссылку на следущую страницу, т.к. в макете нет ссылки

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +        <span class="visually-hidden">Показать список</span>
обернула как список

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +            <input class="range-slider-input" type="range" name="price" min="0" max="9000">
Удалила

2023-08-19 09:49 UTC, Natali34 commented on hotels.html
> +            <input class="number-slider-input" type="number" name="min" min="0" placeholder="от">
Добавила