Базовая стилизация всех страниц
htmlacademy-htmlcss/1413529-sedona-1 pull request #4
Opened 2023-08-29 23:02 UTC by Natali34

2023-08-30 06:04 UTC, Kartaviy-arteom requested changes
+ параметры шрифта не везде соответствует макету, например: заголовки карточек каталога, цвет в карточках на главной

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  font-family: PT Sans;
font-family: "PT Sans", sans-serif;

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  background-size: 100% auto;
background-size - это для background-image, просто для background-color не нужно задавать

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  background-color: #fff;
пиши цвета в соответствии с этим критерием https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  margin-left: 70px;
это не нужно, не надо так выравнивать, обсудим на созвоне

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +.index-title_text_1 {
плохое имя для класса, не соответствует критериям

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  text-align: center;
у этого элемента цвет шрифта #000000

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +.index-title_text_2 {
так же наименование класса

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  font-family: PT Sans;
font-family: "PT Sans", sans-serif; можно вообще не указывать, значение наследуется

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  color: #fff;
здесь и везде формат для цветов

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +  font-family: PT Sans;
шрифт

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +.subscribe-title_text_1 {
наименование класса

2023-08-30 06:04 UTC, Kartaviy-arteom commented on styles/style.css
> +input[type="email"] {
критерий о глобалном селекторе, используй классы

2023-08-31 18:51 UTC, Natali34 commented on styles/style.css
> +  background-size: 100% auto;
поправила

2023-08-31 18:52 UTC, Natali34 commented on styles/style.css
> +  font-family: PT Sans;
поправила

2023-08-31 18:53 UTC, Natali34 commented on styles/style.css
> +  background-color: #fff;
поправила

2023-08-31 19:17 UTC, Natali34 commented on styles/style.css
> +  text-align: center;
добавила цвет шрифта

2023-08-31 19:20 UTC, Natali34 commented on styles/style.css
> +  color: #fff;
исправила

2023-08-31 19:22 UTC, Natali34 commented on styles/style.css
> +  font-family: PT Sans;
поправила

2023-08-31 19:54 UTC, Natali34 commented on styles/style.css
> +input[type="email"] {
убрала footer и address. прописала корректный класс

2023-09-03 11:52 UTC, Natali34 commented on styles/style.css
> +  margin-left: 70px;
поправила

2023-09-03 12:06 UTC, Natali34 commented on styles/style.css
> +.index-title_text_1 {
поправила

2023-09-03 12:06 UTC, Natali34 commented on styles/style.css
> +.index-title_text_2 {
поправила

2023-09-03 12:52 UTC, Natali34 commented on styles/style.css
> +  font-family: PT Sans;
убрала везде, где был "PT Sans", sans-serif;, наследуется от body

2023-09-03 12:52 UTC, Natali34 commented on styles/style.css
> +.subscribe-title_text_1 {
поправила

2023-09-05 06:07 UTC, merged

2023-09-05 06:08 UTC, Kartaviy-arteom approved these changes

2023-09-05 06:08 UTC, Kartaviy-arteom commented on index.html
> +    <main class="head">
подправить оформление + все ошибки валидации в документе

2023-09-05 06:08 UTC, Kartaviy-arteom commented on hotels.html
> +              <img class="logo-html-academy" src="images/index/logo-html-academy-footer.svg" width="114.9" height="32.9"
width="114.9" height="32.9" - допустимы только целые числа

2023-09-05 06:08 UTC, Kartaviy-arteom commented on index.html
> +      <h1 class="visually-hidden">
если оставлять такую разметку нужна будет доп обертка на которой будет фон

2023-09-05 06:08 UTC, Kartaviy-arteom commented on styles/style.css
> +  padding: 11px 0 12px 0;
сама ссылка должна занимать весь квадрат, паддинги должны быть у ссылки

2023-09-05 17:47 UTC, Natali34 commented on hotels.html
> +              <img class="logo-html-academy" src="images/index/logo-html-academy-footer.svg" width="114.9" height="32.9"
Исправила

2023-09-05 17:56 UTC, Natali34 commented on index.html
> +    <main class="head">
поправила

2023-09-05 18:04 UTC, Natali34 commented on index.html
> +      <h1 class="visually-hidden">
сделала обвертку с помощью тега div

2023-09-05 18:11 UTC, Natali34 commented on index.html
> +      <h1 class="visually-hidden">
добавила тег main c классом