Декоративные элементы и состояние
htmlacademy-htmlcss/1413529-sedona-1 pull request #7
Opened 2023-10-21 21:37 UTC by Natali34

2023-10-22 10:02 UTC, Kartaviy-arteom requested changes
1. Необходимо подогнать страницы под pixelpefect
2. тебе не нужно дописывать в разметку disabled всем кнопкам, просто у них должны быть описаны стили. Так внешне должно быть все как в макете

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +  background-color: #68A2CA;
Здесь чтобы соблюсти критерий https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01 нужно писать цвет так: #68a2ca и далее по документу

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +}
здесь нарушается этот критерий https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-03

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +  font-family: PT Sans;
"PT Sans", sans-serif;

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +  opacity: 0.3;
navigation-item-button должен иметь всегда прозрачность .3? в хедере кнопка не должна быть полупрозрачной

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +.navigation-user .navigation-link {
у кнопок не хватает border-radius и горизонтальных падингов

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +  display: inline-block;
input[type="email"] нарушает критерий "Глобальный селектор". И нужно исправить отображение placeholde

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +  box-sizing: border-box;
box-sizing: border-box можно задать глобально и критерий это явно допускает
*,
*::before,
*::after {
  box-sizing: border-box;
}

2023-10-22 10:02 UTC, Kartaviy-arteom commented on styles/style.css
> +  border-color: #000000;
это тоже должно быть на ссылке.

2023-10-22 10:02 UTC, Kartaviy-arteom commented on index.html
> +          <hr class="decor-divider-background">
это вынести в стили, для этого не нужен элемент

2023-10-22 10:02 UTC, Kartaviy-arteom commented on index.html
> +                <img src="images/icons/home.svg" width="77" height="72" alt="Описание жилья.">
эта иконка должна быть в стилях, ее нужно убрать из разметки

2023-10-22 10:02 UTC, merged

2023-10-22 13:20 UTC, Natali34 commented on styles/style.css
> +  background-color: #68A2CA;
Исправлено

2023-10-22 13:28 UTC, Natali34 commented on styles/style.css
> +}
Исправлено

2023-10-22 13:29 UTC, Natali34 commented on styles/style.css
> +  font-family: PT Sans;
исправлено

2023-10-22 13:46 UTC, Natali34 commented on styles/style.css
> +  display: inline-block;
исправлено

2023-10-22 14:19 UTC, Natali34 commented on styles/style.css
> +  box-sizing: border-box;
задала

2023-10-27 17:44 UTC, Natali34 commented on styles/style.css
> +  border-color: #000000;
исправлено