Попапы, слайдеры, формы
htmlacademy-htmlcss/1413529-sedona-1 pull request #8
Opened 2023-10-31 23:24 UTC by Natali34

2023-11-02 17:58 UTC, Kartaviy-arteom approved these changes
1. подправить пиксель пефект
2. Все интерактивные элементы должны иметь состояния

2023-11-02 17:58 UTC, Kartaviy-arteom commented on styles/style.css
> +*,
[тут ](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAzCA7ALgWhQQzBgAJgAddIotLXPAWwEsAbAT3iNJAAUAVIgZTzoAzpwDc5StRzDMLJjHboIAJzp4mEilQw4A7jAYBzABaZ2AFgAMVrZWEqw7AK4qmACk4B6acK8AHTGEhYWxrKwA6PQgUFAAmTgBKHTU8TE8QaNiEkES7HRooBmF-Jjw2ImE9PH8tAF9yclRdWkISSQKcfEZWdk5eARDxDulsWXlFImVUzRGWg2MzdgB2G3yHJyJXD29fAKCQ7FXIrPiklPV0zlOcvLnC4tLy9iqa+sb0Mzomdu0TQ1M5iIAEYbABSd7ocgAKgANDD4PAAEYwNAqGDw9DQxF4FCYGAqX6UJEQAAeYwYAC8GOgjOwSSpYCpsCTSZDyCSoCwiUQiiUyhUUAo2SNhdgiuiwJgGBh2JAmM46Oh8ox0Nh-osgaCrBCOuoVEYaewrEQ8M5MBB8qNuswKv0+IIRJxYZVDsICQwUFaWsIqZNgQAOfwi7RMGkwdUApZEOLA4P5eWqdgAYhsadsHSRBAA1kYVBBnOgoNhEyoU-EK3F8noGFBMCZ2MC4gGrPHyA0oegIv48EYI5AsHhw4SyNo+U9BcKrWKJTApTL0HKIAqlSqaZHNY3wSq8AajUQTWaLdOYOS8xA9I38lmwLn84Xi6Xy7EX9eyWMTHgoBfjQeQQBWYM-2TMBQLA6ta3rRs4hsNt0A7cgIiRc0LQoUcpBaG1eg4bgHSGEAXWCEQxg9L17hkP12BguCMJocYFCUVR1FmbRRgWQEVjWDow3QCMNQ4ogAGYADYaKIfFSRwTAVBCNE6Bcfx-AJMA8HdBNlyTIhkxfV9Mxzc8HxLDSyy0gM4iRQSoEEt9GQJbAZKKZxhF-CwgNc0kDxsplGN4iC6wbGNBLiMSeygIpaWNBNXGETT-AgGl8RUfJxwFdgaR4iMkSYCBbzfclfWpCKiAZJkWTJdku2QzBULGZwkWEMAVAYFF4DQMAnJ5Eq7IchgnJctygIzbQbzvAsiyM7KTOTYSAzwOIVPUybnx0iqkJQjBavqxrmsUEwIAANwJTrVFKnq+r-dyiEuobiX0+9xqfLSZrmhaOke7SdLI+CPjW6qNuEOqGqalqCGlQ7OrusbH2MlMzIsqzFs0j6Vo6CAezABg5GNCJrPbH6ez7SMvyO9Dishwz3s+r7KBS54qCnDpQvCuk-1WQaiDZkMEK7bKjAgHl2pUGKTLihKCXyCScFgSAZOlWUtiLAkMsRqaqZ3Pc1SagTBNbENKDi305cXU16uXc0YHySlsBpWBSSvPHO27Xs+JgYnmV5-nSZrfzG2sMTaYqLKcuzVb0DwfbjDSBceQD9ghVPdXDWNm6iG9qCQSsYTddD8PI6N7Aw1kGPHlS+mE46AArJzpRQFgjKwGAsDlRvEpPck9Bk-x2A7t4OjTgLhOWIM9aIfUk8ixmv2ZifQ2KGQ5AUbA5CUnyLYdxCw4jowo42zGYDoHkx-3FOmZpFmhu5iJN7zhcC5pbNi-5Omg9yyewrPqjdZBUSR+tehbT6LhQYToCKumIu6Jq1NOgUkpJMaiv8fQL0mNMZi3oaDsWjMcfIGUNwCTiO5CWp4pIyREHJOUNRMYaD9IQyS4o5yqB3sbZQvk3owy0umLi2gDaYwXOwdEZQwZr2+o7a+29857zoCWVw6Im57UOiOVhS0tLLH-MJOI-5lg0KlvQ2WvCFZMmVh0SW2AHxK3DNgGIKB3RamHlouhMtGFLxMAwW8vFhDORjGJYxpi3DmO4UbFwiskrry7KIxxPFswsnWmhciMD-Q-zQfPCYjEZiJOwBgoEWDuLmP4tGeBdjpKySYgpJSjhVJCNureAyD02HJhUcJYEGj8inyKsPP8bSU6U0+l5bqX5eoeIIUYoh9iGEBKmBgCp4lhlUKMMbQgDdgnCI3rnMRt8IlRL+ouNqHVSYjWqdDJR01GlWAsAGHOW9wn3w2aheAciSZ6SqfdA5SMGn-hOWckJV8VmXPQJEqqNzQYMHBrs8mNTDn1MaZoxRSM1ao3RpjCokRcZLNCd8-OTl7ljhLnTeOv8ZwMElGM-Meh8hV1kJ6OuA58RNzLuSRuUB8gzLVBIjx8zW56jwO3SCAURK2I5RrAuqIgRHktJ8sJ6KIFEC+Rc-OETD7rn7tBMSqpcF5OClzH64rb4YsJNKm+u98TySwCYEszimBQHcMCZIILHlQ2tuoPsLg3DuAiBELwDAHUwD8C4jAfh3S7jACYCIwh9pGDuMNUFxZ0RKTSIxeyMAY2YGvJG7A-i9FsvFmKtF2rJV6tWQa-e8BjWmuYBauI1qHmjUMh652TqPCuvdZ671A4-D-F3JgYNobw2VKreNaNrsgTKHjYm5NtrDJpvlhmxZl9jH4H2qoPeAtamwu0MYplzcFlpKwnaIBjpRCgKIqECBno0kFX9NnWJ9FkFMQ0GkjJlhOGUBwbkrUF7honV6Y5DxoIxJ7KeSmZYUAkT-gsFAxVMY32UBfZ-f22LJzl20GSmulLdAtxeOjCMu4oaMrDLM62hrWUt0zdoA6BIhQ-iIM4sKjdQ6KhRMyOdC78Q8gncbPApsFT4nUg3GlnBhjaC1tGMIXi0ZUTgpfLVBbJGMaasx0mR9Nabgg+JzV2apPXIwPKtU4HgRZy8dM3DcyiPTp+uodcVKhy8QUaxMU55LwghVimDhJ8ICGz0fwqOh1Vo21PJGfMEMx1gphd0yt+z7W1q2M6xtztvWK1JO6uL2AzNqj-VDCIFd-BhtHb2qNCaB1xv7WkbLYWz1bh1Kac0oqsVP3g3i3zs55yTrNquDoTL8P70I5uxmrmeHyw84I1aEcAYaFYOqWssAYlcJ62M9jMVOOTJ02JaDIJlW7nHkQbAcYR4tPPj0kynSwxdyIIS9wJozsHm7UQUjKhyP2aoxN7ziXpSYEXtIFjU8P5EH-Ft9p6rPKfIBkiZ7i8LPDkfhOOODMbP1YJXOMZ8pFTKiGbQ9dRAp3NI+0VYSABOQa+Rt5HfUSpx2PnyT-HzDiPEmKe1hZrY6yL9a3V069Ql22XhpaqHFEC2sdlUsPk7Vl0LTzh35fGSLorQu7WlYzjqPy6cmywRHstjRv6P0mWYZMqlaGcL8f1tNvRs2zZcczBAP68kYx6Y1STxLgPgfEFJqMaXOsxKO6QSk1BsT70c0fUQZ9UYgQiX07QwppDilbEUspcpjn2EcIx+-IqKcFMz0vqTzadu6FAwYIEaODufSURjOq09bvxmpM9-7h9Kc-dKbiAk6FU1BIN8b3H6e-3tBJ9b5fL8+0hCYBiwFnLE1gsoxRRELvPeYt3yLqTWOtK27pM7t3Tuidj7N8+5XueYwkFLxYCvcZLCR9j8HH2UIEil4XkmzTODkOEOUHbyfTHu3JcU1qXDSyyLKBdOH53qA3ej9eva5It7Pbt1m5n1jAAIkCpMjPrinPg1vDs1kjohtXBSvXNSkCCUAQJlDAJgAYDRq1oZgAZ1uytoATuwM7iPOBuECFA-luIJEBAGIBCPGuoZhusQZfP4HtBaGfnoOgJiN2JwRACWEICwJpvJpyuktymVrqH8OXhVseKjEiBXHDrgJjHHMwCxN-r-r3sfgAUIegCIRfryFfrPqKDDoSu5hePGvImpPyutvfvHo-hGoFs8lNK-gjHXstLpAfj-uPjoXbixvrmARAV5pevnvgi7ogskiXh7qxPMLIVkrPLxKqkCM2EHsQkUmoCUpHjYW3mtivp8oftof-rAJntnqIaEbAo2HyrEXRMXigremXkpuENgjkrIbGKthrMnj9IURPiUdtGUYuMiKiKoMAVNqAWxhxubBLKJq3pQIJkCCnCSGbjPE+kKisaPHkWxpVnLgPJBpRm0b+imo9AaFmO4Oov+C6OcZcf+BcQeDjFYJdlrrxiAPxpob4f-hIuDqXDAfgcYMygRqwcRpQJQYrvkMtoJAwYcc4YPqrFYCgMJPgHYqjujgUT4X-ifoaqgZZtTkQKxnwuAZ5lAcYT8dDuSHAemggaSsgbXKgdrhgYQCyNgbgYgZQKQUJHsTto2MCHQR5JCSPHfjhn8SREwCgC8NJNgYGqtEUBHKVDgqDlZoiCiGiKMXruMewIbvNtMUdinPMesUsRaObpXmsbManJIUQJbmCQcSPHzkFiZCcXgKdi6FYE6U6fcZdl1OrhMsvlsfIdoE8UCHxiAKtD0ToafjaVAF8TilDpQEhigf6YCYspQG1iygmTsRXktrIRCYwcVsLu9DAAiXCcJEiSwWjsZhVB6kYIfOITptuB0MtiKvkBAIocoSgKoWjroJZqtBAhHIQMIJGbVlSeSjSfGaWV1qSfPjUIvr3E4QPp-l4U+hvletvrvhro9rbGnpjCDh2WDtPsSdGbSlzuYU1iuCybiTQeaddPjpOcpkwQZn8amQDgSD2f-oXJgP2dfttueYnpsXqUccuiFrPLIJvhMMudevvpfN2S4h8ZieGe+SYeOeSceYjoOchrSTSiidoMmQCaOcQTTrmcuoWYiX3GaVQUrpmXycWfeThUCWeQ4ewC2PQdmY+SoM+aEOGViTuR0NAfubioeXDhSSeShXGahjSrxfSleUduQYKXhimdRYmaPAqmaXEFJXqOuMtnEMpcTohJBb2boXtHQCqWTNCcznWi6kzk2u6i2l4PpTAALu6SmoVoOoIY5TmXanid-H9gxVbtpU+VBRifvLgBANAP3rTp6qZQ2szs2r6j4EFVAHZa5YZI5QVnlhLjOWFu5bpp5W+hBb5bpafoaHiCFcLiZQzmZdFsfpZdFQVR2iGoLmlcLklWLi5U-uNBlWovQdlT9DpdBfvHBSSVIPikeXMpSZXNSShjxkCBhUmQQbJVNUZbOf+cPsCSRaCcjjgMiWWcxaxUvJuYZeBspXsY7mEYMjUUkgxNEQ0adekvET7lXngtUZQMYiHsIGQuHqUipDkbfj+SaTtmftqV2blcUV6v0UbDyPtSpVddLoGBEbUVEfUSxLRPoLIc0dkkkepVtt6esZyR3l1a7I4CapweAaEP4WIQKhaJJSdYjXEjBggrDedfDXejdevmjZmbXqusMs9a9c4BHmUp9VMrQhzrovLKuR4VpCunhXau9BCk0ibrZMyGdAMtQXRUQG0m8lpV2P6vjeqKbkTTtS9ooNsn2TagtYcq8u8gDQGgTTrUwMTbtbctdkVZLbUmbachbVrYTTbXrQxICsCi1S4QBqopCtHsjPOVdvCljHccijlZbdrfiJ7fKTidxTfrRS3tjj-OyZTQeYhcNYJb8TJdhXNWyfkmtdgBtWOctT7DLtIRBYDNtCiH1TxYNfxUhS1phTNQXZtfVU7YcuLfNaFRFtsO4OVSzqTl4FlK4JtJniiCyJGulplvZdCY1UOs1V3YZFDeCHIVVhXfLjBHscthYI0h0XYavgnl2bXcDBGLxHoMIAoNVDiUdZUeyTDWddeqXldV7gkQuSzUpoHrecHiQi9WHtze9VHqLSHbEJRbMg+bkZ0X+A2W-KnenSaPAjjY7IDlPRGDSHJIwjyA-XAoXpenUTegjdAl7ijYkS7NXmzR-otaHcwVRXNZQSokfcfJvSfUYGVMsV9idTXVtBfYFWoA3cneBjNDwz9DSP4OaNgPvEOD8LuTVmlOgDgi-CHMRZXdqNIVBrIf+AQ++nLavHtvZH0udNdBdFCTluWHEJWFuv-NhDSOTpjHlDAp9h6WVCPPItKCpEwKXSWYwGFAoOw0qh5MXSPhI1IzI8wIiE8IQHtOajie9M5jYz0DugMHus6GAkeqRKevntDbTS-e7pdVTWQ7da0dXmI2g+fTtEQGE5gHweg3XcQP8uUdVhDtU0o+Yio-kB4y4hoD41RX41AAE7Etuoow40mp8gTBGGgDrdZpfgo-BTGWNWhegRhoyTgTAHgVwueX7B5JzE-fyd9YsX+T3QBZfNM4lGMDlAwBoFWVyuoxYLo3M60-1aaO3R1tA2c0FRcz6oYfQ1A3JYExnGJILMLOwKLOXe2YcgGIJPDO-q80Ke6CKWKeiJgJKZ8uc3ZD85UKGvbfIkuqbbNPNHgKtBi8yD861DlDsmA89ESyS185iwOPAD7YZWjAQAitjHC8cUYKcaCBYC6JlZcVYHEK6YJOGp8zM5cxjL06+UI3Vu3AvqnEvqYWSbDo1sbMSpjT9V+S0UBUucvGBZMsYoLYwgY+i-S8yDFFK9458V7CRcsBmU0XsUnSPFhe8wC6NUOeNWgR8z9BZlKEbVxXucnbxdnXwheJq-YS3hfL6x2f69bOgNg6DfJopZXcsCE7fmpdoxyQ-vZI62kX0-8xhZfH60EPG4m7fBwRMrg3no-Ts0XnDcQ4zY68zZQwJHWyXZzUAzzR9Ya8Msa2MiLX6bUok58iWyfgmzevnJW7xLiwSHwWO2W5OxW3tDO4bfi0jNLVCiPgu1g0uxtNO4oMy+u3adyw6cCMCMsC6NjpeyrTe0imK90SSFI5LLK9Jf8W63NQKQg2vqtF8GUCpLAHQHXHKqTcfWAyOyPn+wQMTEB3fL8rO7M5Cxu4HTLZB5gN8NB4B8B-fBS+1AG0O+Cih1u5fFBwB-vNh-B0e6TFyzyxe1ezewGHezjA+47HQNAL0wnYh+5a2aSDAAykYjMUaXiOsc62mVXZaUphowlbaXwqe2cQ85cQpzGEp5EC2Cx4hGx1ABx9uVZiWNlO6HBYO5fJpzc6TO5f1pAZq-A6vTJ2LQBcSGrkY1+mQdm8rcJJdJzE48IJ+N+PZsg4wV9l-CaPaY6QeC6XcY0up12CZ945rYGmDWacsBe+rREDF3p65plNEgEWqSbHNlMd+6fWo+nDow6wJCV9aY5wrVRNQ33fhT3VYw13tqazZ7lomslSOn7amoEUZhCyC7FPFL1yJQGS8UGQJ0du52JLqV9ro8W7oPmN4002qGAPp4Ze5Rqfl6ujMem77sadt+xSVYPcPVFSIF4Mtxl-FZ10vc5SleM0OxNYArrmjtFP12LPJexe5Yw2acCJnctt9yl2l2d+6BpouHcoh+xXmcJPmfmatADyt8D7h05BIfWDSI7c-oclD5D0WajOaBlGQUBHNrWKZDC2-jD+x944D5l5sky-OL7S1zCSmBj9D+B7HnCmyxHUiqT1p94yTbYfkTA0nJwwaewBN3k7QMk4Aqk-hIRG6FkxUZMBDVTVegUyQ2xEzS0d-drDVwkyz+zf-RkebsA9kUItHVrXJFKq2eAcWAZP4FWbA9+QKvqRAObqcs-WLwAjhJLyAtL+ArL5DWEYdZEfTY240QJJ-b7qU3gpnU9QA69SpP4JQmGLAsHRB0898Y3b5j3Edpn2+4QT647MYnFyalp3JuRKMx6Ld4rzkzV67g22-UU8jSUxr3khjcz+mAUjH2HoO-rDmwoMJwBPa95V2GuioE1N3t48X4ZV0hoqhyb4GgI9JgwJbwl5XRYO2zIU0Q9SnZ9k2EBHt5V8Y4rdacczCg1-EE13vprsOzr1TSMx73hF7xkyRJAtk4-bk-W0H3X6Q2r6ja23kuUz5THTkgqFLeCHVHrZ2TCM8seI+QvvP2AHmoEe+HSgAWBezhg8eHkAnhGWTDQsAAQoJAAAiUdXGoAKYhwCoA1PQRDyGQG49PE6A5cIT1TDX9au3dJGAADE4gbAtgW7Tn4T8wBxYA7lFkiqVUTuXjelLuAu508ru4uCvkwPHTdc+EmoG8u61YjqELE4dRFDjC4Empdwo-XpjwNA7rgpu4Rfkim3lzckUuMA2AD2BUCYBXAEYPQbz0UwCQ3+qlbTF92BC45B+V8OjHZC-DOAmAb5fQY4OjAWA2al8IwM4C9Slt0A3g5kL4P8G28BeU3AMNUVn4mogB4QyIYgNNLqMf0ZFDfkrRbx-cPIuQwxlVyujmMwslMU-lWFlreQL+kDHrrhSQ5TQU+0CW-vaGAT7pvemTZ-nLyqKu8leF1FXnESUxh87qeSTqqxxpBOQ+CpQKlmM [...]

2023-11-02 17:58 UTC, Kartaviy-arteom commented on styles/style.css
> +  position: relative;
все интерактивные элементы должны иметь состояния

2023-11-02 19:42 UTC, Natali34 commented on styles/style.css
> +  position: relative;
исправила

2023-11-02 20:59 UTC, Natali34 commented on styles/style.css
> +*,
Артём, классный сайт!!!! Огонь!!!! С

2023-11-04 18:19 UTC, Natali34 commented on styles/style.css
> +*,
Я исправления сделала, только про цвета система пишет

2023-11-06 20:18 UTC, Kartaviy-arteom requested changes
pagination-link-interspace - у этой кнопки пагинации нет состояний
проверь отображение в firefox - input number, отображение футера, селект

2023-11-06 20:18 UTC, Kartaviy-arteom commented on styles/style.css
> +  position: relative;
на каждой странице должна быть текущая ссылка и она должна быть подчеркнута

2023-11-06 20:18 UTC, Kartaviy-arteom commented on styles/style.css
> +  max-width: 300px;
кнопка в хедере при ховере не должна получать прозрачность. Так же у нее нет горизонтальных паддингов и текст может прилипать к краям

2023-11-06 20:18 UTC, Kartaviy-arteom commented on styles/style.css
> +  background-image: url("../images/index/index-main-background.jpg");
здесь фон может вылезать за блок, такого быть не должно

2023-11-06 20:18 UTC, Kartaviy-arteom commented on styles/style.css
> +.index-subtitle-container {
нужны горизонтальные паддинги

2023-11-06 20:18 UTC, Kartaviy-arteom commented on styles/style.css
> +.input-border-left {
в этих инпутах введенный текст не должен наползать на "от" или "до"

2023-11-06 20:18 UTC, Kartaviy-arteom commented on styles/style.css
> +.input-email {
у плейсхолдера и введенного текста должен быть разный цвет

2023-11-06 20:18 UTC, merged

2023-11-07 17:27 UTC, Natali34 commented on styles/style.css
> +  background-image: url("../images/index/index-main-background.jpg");
зада ширину и высоту

2023-11-07 17:51 UTC, Natali34 commented on styles/style.css
> +.index-subtitle-container {
проставила

2023-11-07 18:08 UTC, Natali34 commented on styles/style.css
> +  max-width: 300px;
исправила

2023-11-07 18:22 UTC, Natali34 commented on styles/style.css
> +  position: relative;
исправлено

2023-11-07 18:36 UTC, Natali34 commented on styles/style.css
> +.input-email {
проставила opacity, как в макете